apiVersion: apps/v1
kind: Deployment
metadata:
  name: socialmedia-deployment
  labels:
    app: socialmedia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: socialmedia
  template:
    metadata:
      labels:
        app: socialmedia
    spec:
      containers:
        - name: socialmedia-app
          image: social-media:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
