apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore
  template:
    metadata:
      labels:
        app: bookstore
    spec:
      containers:
        - name: bookstore
          image: ayushranjan02/bookstore-backend:v1
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-service
spec:
  type: ClusterIP
  selector:
    app: bookstore
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
