services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: react-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app # live code mounting
      - /app/node_modules # keep container's node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
