version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    environment:
      FRONTEND_API_URL: "http://auth:8081"
      ORDERS_API_URL: "http://orders:8082"
      INVENTORY_API_URL: "http://inventory:8083"
      DB_USER: "admin"
      DB_PASSWORD: "password"

  auth:
    build: ./auth
    ports:
      - "8081:8081"
    environment:
      DB_USER: "admin"
      DB_PASSWORD: "password"

  orders:
    build: ./orders
    ports:
      - "8082:8082"
    environment:
      DB_USER: "admin"
      DB_PASSWORD: "password"

  inventory:
    build: ./inventory
    ports:
      - "8083:8083"
    environment:
      DB_USER: "admin"
      DB_PASSWORD: "password"
