version: '3.8'

services:
  social-media-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: social-media-app:latest
    container_name: social-media-app
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

networks:
  default:
    driver: bridge
