version: '3'
services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4201:4201"
    volumes:
      - ./dist/angular-14-example:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
