apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  # The values must be base64 encoded.
  # For example, "rootpassword" encoded is "cm9vdHBhc3N3b3Jk"
  mongo-root-username: YWRtaW4
  mongo-root-password: c2VjcmV0MTIz