apiVersion: v1
kind: Service
metadata:
  name: social-media-service
  labels:
    app: social-media
spec:
  selector:
    app: social-media
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
  sessionAffinity: ClientIP
