version: "3.9"
services:
  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8082:8082"

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8083:8083"
      