apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  FRONTEND_API_URL: "http://auth-service:8081"
  ORDERS_API_URL: "http://orders-service:8082"
  INVENTORY_API_URL: "http://inventory-service:8083"
