apiVersion: v1
kind: Service
metadata:
  name: ping-server-service
  labels:
    app: ping-server
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: ping-server

---
apiVersion: v1
kind: Service
metadata:
  name: ping-server-nodeport
  labels:
    app: ping-server
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: ping-server
