apiVersion: apps/v1
kind: Deployment
metadata:
  name: social_media_deployed
  labels:
    app: social-media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social-media
  template:
    metadata:
      labels:
        app: social-media
    spec:
      containers:
        - name: fastapi_container
          image: dhruvdoshi32432/social-media:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "250m"
              memory: "200Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"
