apiVersion: v1
kind: Pod
metadata:
  name: social-media-fastapi
  labels:
    app: social-media
spec:
  containers:
    - name: fastapi-container
      image: dhruvdoshi32432/social-media:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
      resources:
        limits:
          memory: "200Mi"
        requests:
          memory: "100Mi"