apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-media-deployment
  labels:
    app: social-media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social-media
  template:
    metadata:
      labels:
        app: social-media
    spec:
      containers:
      - name: fastapi
        image: your-dockerhub-username/social-media:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "500m"
            memory: "200Mi"
