apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-frontend
  template:
    metadata:
      labels:
        app: inventory-frontend
    spec:
      containers:
      - name: inventory-frontend
        image: inventory-frontend:latest
        imagePullPolicy: Never   # 👈 THIS is the important line
        ports:
        - containerPort: 80
