version: '3.8'

services:
  jenkins:
    build: ./jenkins
    container_name: jenkins-server
    ports:
      - "8080:8080"   # Jenkins Web UI
      - "50000:50000" # For Jenkins agents
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Allow Jenkins to use host Docker
    restart: unless-stopped

volumes:
  jenkins_home: