apiVersion: apps/v1
kind: Deployment
metadata:
  name: socialmedia-deployment
  labels:
    app: socialmedia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: socialmedia
  template:
    metadata:
      labels:
        app: socialmedia
    spec:
      containers:
      - name: socialmedia-app
        image: nginx:latest   # placeholder for social media app
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
