apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsfeed-app-deployment
  labels:
    app: newsfeed-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: newsfeed-app
  template:
    metadata:
      labels:
        app: newsfeed-app
    spec:
      containers:
        - name: newsfeed-app
          image: abhi25022004/newsfeed-app:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
