apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-express-config
data:
  ME_CONFIG_MONGODB_SERVER: mongodb-service   # Must match the MongoDB service name
  ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"