apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  # base64 encoded values: echo -n 'admin' | base64 → YWRtaW4=
  mongo-root-username: YWRtaW4=
  # echo -n 'password' | base64 → cGFzc3dvcmQ=
  mongo-root-password: cGFzc3dvcmQ=